### ISSUE TITLE
Error launching games with Yaba Sanshiro 2 Pro emulator

### ISSUE THREAD

**Issue by ligredesubi** [TapiocaFox/Daijishou#434]
I'm using Android 13 and launching the games withing Taba Sanshiro works right, but inside Daijishou I always have this error:

`android.content.ActivityNotFoundException: Unable to find explicit activity class {org.devmiyax.yabasanshioro2.pro/org.uoyabause.android.Yabause}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2197)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
 at android.app.ContextImpl.startActivity(ContextImpl.java:1111)
 at android.app.ContextImpl.startActivity(ContextImpl.java:1082)
 at android.content.ContextWrapper.startActivity(ContextWrapper.java:442)
 at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playIt(DaijishouLibraryModel.kt:622)
 at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playItWithRules(DaijishouLibraryModel.kt:674)
 at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem(DaijishouLibraryModel.kt:744)
 at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play(DaijishouLibraryModel.kt:757)
 at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$default(DaijishouLibraryModel.kt:537)
 at com.magneticchen.daijishou.nav_fragments.PlatformLibraryGridViewNavFragment$onCreateView$4.invoke(PlatformLibraryGridViewNavFragment.kt:456)
 at com.magneticchen.daijishou.nav_fragments.PlatformLibraryGridViewNavFragment$onCreateView$4.invoke(PlatformLibraryGridViewNavFragment.kt:455)
 at com.magneticchen.daijishou.daijishou_recycler_view.DaijishouRecyclerView$Adapter$ViewHolder._init_$lambda$0(DaijishouRecyclerView.kt:238)
 at com.magneticchen.daijishou.daijishou_recycler_view.DaijishouRecyclerView$Adapter$ViewHolder.$r8$lambda$dcH5ow6HzTN0-BP2tsljWiEUDBs(Unknown Source:0)
 at com.magneticchen.daijishou.daijishou_recycler_view.DaijishouRecyclerView$Adapter$ViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
 at android.view.View.performClick(View.java:7560)
 at android.view.View.performClickInternal(View.java:7533)
 at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
 at android.view.View$PerformClick.run(View.java:29754)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8152)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)`

**Comment by ironrock02** [comment]
Hey it seems to be related with Android 13 update? I have the same error with some android emulators as Drastic, M64 Plus FZ and Dolphin, shows the error unable to find... RetroArch 64 all cores and Citra still working.

**Comment by ironrock02** [comment]
`android.content.ActivityNotFoundException: Unable to find explicit activity class {org.mupen64plusae.v3.fzurita/paulscode.android.mupen64plusae.SplashActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2225)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1863)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1111)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1082)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:442)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playIt(DaijishouLibraryModel.kt:624)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playItWithRules(DaijishouLibraryModel.kt:676)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem(DaijishouLibraryModel.kt:746)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play(DaijishouLibraryModel.kt:762)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$default(DaijishouLibraryModel.kt:539)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment.onCreateView$lambda$21(PlatformLibraryListViewNavFragment.kt:777)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment.$r8$lambda$ohdwl6z9y-ShlW422Au6axrohpQ(Unknown Source:0)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment$$ExternalSyntheticLambda6.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7559)
	at android.widget.CompoundButton.performClick(CompoundButton.java:146)
	at android.view.View.performClickInternal(View.java:7536)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29660)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
`

**Comment by ironrock02** [comment]
Drastic:

`android.content.ActivityNotFoundException: Unable to find explicit activity class {com.dsemu.drastic/com.dsemu.drastic.DraSticActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2225)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1863)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1111)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1082)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:442)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playIt(DaijishouLibraryModel.kt:624)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playItWithRules(DaijishouLibraryModel.kt:676)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem(DaijishouLibraryModel.kt:746)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play(DaijishouLibraryModel.kt:762)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$default(DaijishouLibraryModel.kt:539)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment.onCreateView$lambda$21(PlatformLibraryListViewNavFragment.kt:777)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment.$r8$lambda$ohdwl6z9y-ShlW422Au6axrohpQ(Unknown Source:0)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment$$ExternalSyntheticLambda6.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7559)
	at android.widget.CompoundButton.performClick(CompoundButton.java:146)
	at android.view.View.performClickInternal(View.java:7536)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29660)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
`

**Comment by ligredesubi** [comment]
> Hey it seems to be related with Android 13 update? I have the same error with some android emulators as Drastic, M64 Plus FZ and Dolphin, shows the error unable to find... RetroArch 64 all cores and Citra still working.

With M64 Plus and Dolphin I don't have any issues. With some emulators I have to concede permissions to access the data.

**Comment by Post-Mortem** [comment]
> I'm using Android 13 and launching the games withing Taba Sanshiro works right, but inside Daijishou I always have this error:
> 
> `android.content.ActivityNotFoundException: Unable to find explicit activity class {org.devmiyax.yabasanshioro2.pro/org.uoyabause.android.Yabause}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>? at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2197) at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839) at android.app.ContextImpl.startActivity(ContextImpl.java:1111) at android.app.ContextImpl.startActivity(ContextImpl.java:1082) at android.content.ContextWrapper.startActivity(ContextWrapper.java:442) at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playIt(DaijishouLibraryModel.kt:622) at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playItWithRules(DaijishouLibraryModel.kt:674) at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem(DaijishouLibraryModel.kt:744) at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play(DaijishouLibraryModel.kt:757) at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$default(DaijishouLibraryModel.kt:537) at com.magneticchen.daijishou.nav_fragments.PlatformLibraryGridViewNavFragment$onCreateView$4.invoke(PlatformLibraryGridViewNavFragment.kt:456) at com.magneticchen.daijishou.nav_fragments.PlatformLibraryGridViewNavFragment$onCreateView$4.invoke(PlatformLibraryGridViewNavFragment.kt:455) at com.magneticchen.daijishou.daijishou_recycler_view.DaijishouRecyclerView$Adapter$ViewHolder._init_$lambda$0(DaijishouRecyclerView.kt:238) at com.magneticchen.daijishou.daijishou_recycler_view.DaijishouRecyclerView$Adapter$ViewHolder.$r8$lambda$dcH5ow6HzTN0-BP2tsljWiEUDBs(Unknown Source:0) at com.magneticchen.daijishou.daijishou_recycler_view.DaijishouRecyclerView$Adapter$ViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:6) at android.view.View.performClick(View.java:7560) at android.view.View.performClickInternal(View.java:7533) at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0) at android.view.View$PerformClick.run(View.java:29754) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:8152) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)`

Has this been resolved?

**Comment by Jetup13** [comment]
Going through old issues. Seems to be resolved with the newest player start argument, yabasanshiro 2 update, and/or Odin update
