### ISSUE TITLE
Cannot launch 3ds games with custom player utilizing Citra Enhanced.  See comment for error. 

### ISSUE THREAD

**Issue by preachermantx80** [TapiocaFox/Daijishou#542]
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW flg=0x14008001 cmp=org.gamerytb.citra_emu/org.citra.emu.ui.EmulationActivity (has extras) } from ProcessRecord{23dcfc4 11045:com.magneticchen.daijishou/u0a675} (pid=11045, uid=10675) not exported from uid 10738
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2791)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1801)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1145)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1116)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:441)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playIt(DaijishouLibraryModel.kt:624)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playItWithRules(DaijishouLibraryModel.kt:676)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem(DaijishouLibraryModel.kt:746)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play(DaijishouLibraryModel.kt:762)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$default(DaijishouLibraryModel.kt:539)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment.onCreateView$lambda$21(PlatformLibraryListViewNavFragment.kt:777)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment.$r8$lambda$ohdwl6z9y-ShlW422Au6axrohpQ(Unknown Source:0)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment$$ExternalSyntheticLambda6.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16220)
	at android.widget.CompoundButton.performClick(CompoundButton.java:157)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30891)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1307)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1388)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:1026)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1942)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1815)

**Comment by mjkaye** [comment]
This looks as if Citra Enhanced has the same issue that mainline Citra had before a [PR of mine](https://github.com/citra-emu/citra/pull/6996) was merged. Given the length of time since the previous Citra Enhanced release, it seems unlikely it will be fixed.

**Comment by preachermantx80** [comment]
> This looks as if Citra Enhanced has the same issue that mainline Citra had before a [PR of mine](https://github.com/citra-emu/citra/pull/6996) was merged. Given the length of time since the previous Citra Enhanced release, it seems unlikely it will be fixed.

I changed it to MainActivity and was at least able to launch Citra Enhanced when I pick a game in Daijishou.  However, I still have to pick the game within Citra Enhanced.  Is there any fixing it from here?

**Comment by mjkaye** [comment]
> I changed it to MainActivity and was at least able to launch Citra Enhanced when I pick a game in Daijishou. However, I still have to pick the game within Citra Enhanced. Is there any fixing it from here?

I'm not a core Daijishou developer, but my understanding is that it is not possible to resolve from the Daijishou end.

Strictly speaking, it is possible to modify an apk (Citra Enhanced in this case) to update the `AndroidManifest.xml`, using software called `apktool`. However, it's not straightforward and requires aligning and signing the modified apk.

**Comment by Post-Mortem** [comment]
This issue needs to be fixed on Citra's end, not Daijisho. Actually, you may be even able to reproduce the same issue on different frontends. Something similar happens with any official beta or dev version of Dolphin emulator; The first time you select a gamecube game (on any frontend) it will launch Dolphin Emulator and immediately go back to the frontend's game selection screen, so you have to select the game again and it then will launch the game correctly. I've tested this with 3 different frontends on different devices and i get the same results. This issue does not happen on Dolphin forks(MMJR2 and below) though. This needs to be fixed by the emulator's developer.  Closing Issue.
