### ISSUE TITLE
Loading .xml scraped data fails on RG353V

### ISSUE THREAD

**Issue by TheMasterWho** [TapiocaFox/Daijishou#544]
Loading a .xml file on an RG353V console for a system appears to take time to load but does not result in any observable change after it is done. Logs include an error message: 
```
java.net.MalformedURLException: no protocol: index.json
	at java.net.URL.<init>(URL.java:601)
	at java.net.URL.<init>(URL.java:498)
	at java.net.URL.<init>(URL.java:447)
	at com.magneticchen.daijishou.utils.Utils.readEntireTextFromURL(Utils.kt:528)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel$applyPlatformPreviewMediaPackIndexJsonToPlatform$1.invokeSuspend(DaijishouLibraryModel.kt:344)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by TheMasterWho** [comment]
Additional context:
Roms, gamelist.xml, and media are all on a second SD card
My system is also unable to load media using the import preview media button. I can grab the logs for that too if it helps, wanted to create just one issue ticket for the main problem. 

If this is an issue specific to the RG353 handhelds I would be happy to try and fix it myself, I have a bit of Android development experience.
