### ISSUE TITLE
Daijisho crashing everytime I try to edit a game cover

### ISSUE THREAD

**Issue by VREvolver** [TapiocaFox/Daijishou#577]
Everytime I try to edit any game (by pressing and holding onto it) Daijisho crashes. This is happening on every platform I try. It doesn't even open up the options to edit, it simple crashes as soon as I hold any game cover with my finger or with a physical button.

I'm using AYN Odin 2 Pro running Android 13, Daijisho v1.4.67

java.io.IOException: Error on service connection.
	at com.google.android.gms.auth.zzl.zzh(com.google.android.gms:play-services-auth-base@@18.0.4:8)
	at com.google.android.gms.auth.zzl.zza(com.google.android.gms:play-services-auth-base@@18.0.4:15)
	at com.google.android.gms.auth.zzl.getToken(com.google.android.gms:play-services-auth-base@@18.0.4:3)
	at com.google.android.gms.auth.zzl.getToken(com.google.android.gms:play-services-auth-base@@18.0.4:1)
	at com.google.android.gms.auth.zzl.getToken(com.google.android.gms:play-services-auth-base@@18.0.4:6)
	at com.google.android.gms.auth.GoogleAuthUtil.getToken(com.google.android.gms:play-services-auth-base@@18.0.4:3)
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:258)
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:283)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:880)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:525)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:466)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:576)
	at com.magneticchen.daijishou.google_drive.GoogleDrive.listAllFiles(GoogleDrive.kt:250)
	at com.magneticchen.daijishou.google_drive.GoogleDrive.createOrUpdateFileByInputStreamContent(GoogleDrive.kt:288)
	at com.magneticchen.daijishou.google_drive.GoogleDrive.createOrUpdateFileByFilenameAndInputStream(GoogleDrive.kt:302)
	at com.magneticchen.daijishou.google_drive.GoogleDrive.uploadByteArrayToFilename(GoogleDrive.kt:321)
	at com.magneticchen.daijishou.google_drive.GoogleDrive$setupGoogleSignInAccount$1.invokeSuspend(GoogleDrive.kt:365)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at com.google.android.gms.internal.auth.zza.zzb(com.google.android.gms:play-services-auth-base@@18.0.4:2)
	at com.google.android.gms.internal.auth.zzd.zze(com.google.android.gms:play-services-auth-base@@18.0.4:5)
	at com.google.android.gms.auth.zzl.zzb(com.google.android.gms:play-services-auth-base@@18.0.4:2)
	at com.google.android.gms.auth.zzf.zza(Unknown Source:6)
	at com.google.android.gms.auth.zzl.zzh(com.google.android.gms:play-services-auth-base@@18.0.4:6)
	... 24 more

**Comment by VREvolver** [comment]
Okay, seems like it was an issue with Google Play Services. I've updated it and the issue didn't go away, but searching a little bit I found a tip saying to clear Play Services Cache/Data and after doing it Daijisho stoped crashing. Let's see how long it's gonna stay like that...

**Comment by Jetup13** [comment]
Now that's interesting seems like Daijisho hung for you trying to generate a token(?) Not sure why though 🤔. Hopefully TF can look at this when they have time
