### ISSUE TITLE
Retroarchivement Login not working

### ISSUE THREAD

**Issue by andiweli** [TapiocaFox/Daijishou#590]
The login in Daijishou seems to not connect to the Retroarchivement Servers. 

Inside Retroarch it works. 

Thanks for checking.

**Comment by andiweli** [comment]
Update

Seems to be a common problem for some time 😯

https://www.reddit.com/r/ANBERNIC/comments/10jq4bk/retroachievements_widget_not_loading_daijisho_353m/

**Comment by cmdrrom** [comment]
I'm in the same boat. It was working on my Odin 1 and briefly on my Odin2, but now both don't work as of this posting.

**Comment by Alvabeta1993** [comment]
Worked completely fine on my Odin 2, but retroachievements web recently got updated and that messed up everything. Hope it get fixed son I use the Retroachievements widget a lot :(

**Comment by dschibster** [comment]
```
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=[https://retroachievements.org/login]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:912)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:851)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:345)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager.login(RetroAchievementsManager.kt:190)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager.login(RetroAchievementsManager.kt:250)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager.access$login(RetroAchievementsManager.kt:50)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager$login$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

This is the most common stack trace that I am getting. Very obviously a RAWeb issue unfortunately.

Some previous errors also showed something about enabling cookies.

```
org.jsoup.helper.ValidationException: The parameter 'cookies' must not be null.
	at org.jsoup.helper.HttpConnection.cookies(HttpConnection.java:302)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager.fetchMyRetroAchievementUserId(RetroAchievementsManager.kt:847)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager$fetchMyRetroAchievementUserId$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Macpiper1** [comment]
Yeah Getting the same issue. the games still track and save achievements which is fine but i love the idea of the widget and know it has worked in the past 


LOG for reference

org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=[[https://retroachievements.org/login](https://retroachievements.org/login?fbclid=IwAR1hzy1ts9H9NE3hWL7dVVEqUit0oDIP7hT3ukhncCQHIwSQJNIGi6yp1tM)]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:912)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:851)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:345)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager.login(RetroAchievementsManager.kt:190)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager.login(RetroAchievementsManager.kt:250)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager.access$login(RetroAchievementsManager.kt:50)
	at com.magneticchen.daijishou.retro_achievements.RetroAchievementsManager$login$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by Cacha21** [comment]
Same issue here.

**Comment by UrDone4** [comment]
Looking at the error. We are getting a 403, which means the connection is being blocked by RetroAchievements. 

When searching about getting 403 errors using jsoup, it seems like maybe the fix is to provide a user agent similar to this:

jsoup.connect("https://retroachievements.org/login").userAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36")

**Comment by djusHa** [comment]
Same here, no login possible.

Same Errormessage in the Logs.

**Comment by sammcj** [comment]
I went to look at fixing the issue but found that Daijishou isn't open source 😢 https://github.com/TapiocaFox/Daijishou/issues/596

**Comment by Alvabeta1993** [comment]
Still not any update on this problem? Come on man, retroachievement widget is actually the only thing i actually use from Dajisho

**Comment by wescopeland** [comment]
Hello!

Daijishou needs to send an identifying user agent for calls to our server. Please do not simulate a web browser; identify yourself as Daijishou.

A valid user agent might be:

```
Daijishou/1.4.68 (+https://github.com/TapiocaFox/Daijishou)
```

If anyone is working on this issue and needs support from the RetroAchievements side, please don't hesitate to reach out to me directly!

**Comment by UScr00ge** [comment]
Reproduced issue on my Retroid Pocket 4 Pro. I sent _way_ too long troubleshooting this issue since it seemingly worked fine on my old Retroid Pocket 3. Glad to know it's not just an issue for me or specifically with the RP4 Pro.

**Comment by nascentt** [comment]
> Still not any update on this problem? Come on man, retroachievement widget is actually the only thing i actually use from Dajisho

the sole dev has stepped away for a bit.  as it's closed source now one else can contribute.

**Comment by CalamityJenn** [comment]
Hi, I am encountering this issue aswell on RP5, the RA widget cannot connect. My Web API key is correct as I can see my RA progression on every game's details.
Is there something I can do to get this widget to work?
