### ISSUE TITLE
I can't log in to my Google account on Daijisho.

### ISSUE THREAD

**Issue by ssoo0521** [TapiocaFox/Daijishou#602]
here's the log.

com.google.api.client.googleapis.extensions.android.gms.auth.UserRecoverableAuthIOException
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:288)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:880)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:525)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:466)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:576)
	at com.magneticchen.daijishou.google_drive.GoogleDrive.listAllFiles(GoogleDrive.kt:250)
	at com.magneticchen.daijishou.google_drive.GoogleDrive.createOrUpdateFileByInputStreamContent(GoogleDrive.kt:288)
	at com.magneticchen.daijishou.google_drive.GoogleDrive.createOrUpdateFileByFilenameAndInputStream(GoogleDrive.kt:302)
	at com.magneticchen.daijishou.google_drive.GoogleDrive.uploadByteArrayToFilename(GoogleDrive.kt:321)
	at com.magneticchen.daijishou.google_drive.GoogleDrive$setupGoogleSignInAccount$1.invokeSuspend(GoogleDrive.kt:365)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.google.android.gms.auth.UserRecoverableAuthException: BadAuthentication
	at com.google.android.gms.auth.zzl.zzg(com.google.android.gms:play-services-auth-base@@18.0.4:20)
	at com.google.android.gms.auth.zzl.zzb(com.google.android.gms:play-services-auth-base@@18.0.4:4)
	at com.google.android.gms.auth.zzf.zza(Unknown Source:6)
	at com.google.android.gms.auth.zzl.zzh(com.google.android.gms:play-services-auth-base@@18.0.4:6)
	at com.google.android.gms.auth.zzl.zza(com.google.android.gms:play-services-auth-base@@18.0.4:15)
	at com.google.android.gms.auth.zzl.getToken(com.google.android.gms:play-services-auth-base@@18.0.4:3)
	at com.google.android.gms.auth.zzl.getToken(com.google.android.gms:play-services-auth-base@@18.0.4:1)
	at com.google.android.gms.auth.zzl.getToken(com.google.android.gms:play-services-auth-base@@18.0.4:6)
	at com.google.android.gms.auth.GoogleAuthUtil.getToken(com.google.android.gms:play-services-auth-base@@18.0.4:3)
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:258)
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:283)
	... 17 more

Is there anyone who can help? My device is Odin2. I also have Odin Lite and I can't find that error in Odin Lite.

**Comment by kraniumet** [comment]
I have basically the exact same issue on my Odin 1. Clicking the "login to drive" button does nothing, and shows up like this in the log. I've cleared the app cache and restarted, with no difference. Works good on Odin 2 portal, for me.
