### ISSUE TITLE
Unable to find explicit activity class... 

### ISSUE THREAD

**Issue by LLuanZZ** [TapiocaFox/Daijishou#655]
I'm having this error when I open Midnight Club L.A on PPSSPP.  It's especially with this game, since in Formula 1 2006 it opens normally.  (Sorry for my English, I'm using a translator)

	android.content.ActivityNotFoundException: Unable to find explicit activity class {org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?

	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2168)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1811)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1101)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1072)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:432)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playIt(DaijishouLibraryModel.kt:624)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playItWithRules(DaijishouLibraryModel.kt:676)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem(DaijishouLibraryModel.kt:746)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play(DaijishouLibraryModel.kt:762)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$default(DaijishouLibraryModel.kt:539)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment.onCreateView$lambda$21(PlatformLibraryListViewNavFragment.kt:777)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment.$r8$lambda$ohdwl6z9y-ShlW422Au6axrohpQ(Unknown Source:0)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryListViewNavFragment$$ExternalSyntheticLambda6.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7527)
	at android.widget.CompoundButton.performClick(CompoundButton.java:146)
	at android.view.View.performClickInternal(View.java:7494)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29367)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/179
