### ISSUE TITLE
retroachievement

### ISSUE THREAD

**Issue by bobbywong9411** [TapiocaFox/Daijishou#713]
When I click on Retroachievement in setting, it force closed the frontend. It still connected to the retroachievement server. I try to reinstall on play store but still don't solve the problem and now I even cannot connect to the server.

**Comment by TapiocaFox** [comment]
Could you turn on the debug mode by typing `\debug on` in logger. Crash it again, and find the error thrown in the logger.

**Comment by bobbywong9411** [comment]
> Could you turn on the debug mode by typing `\debug on` in logger. Crash it again, and find the error thrown in the logger.

java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2642)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2603)
	at java.util.Formatter.parse(Formatter.java:2558)
	at java.util.Formatter.format(Formatter.java:2505)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2870)
	at com.magneticchen.daijishou.settings_nav_fragments.RetroAchievementsSettingsNavFragment.onCreate(RetroAchievementsSettingsNavFragment.kt:62)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3099)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7971)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by bobbywong9411** [comment]
I also try to install daijiso on my phone, the same bug appears.

**Comment by TapiocaFox** [comment]
Is the logs you reported marked as error?

**Comment by bobbywong9411** [comment]
> Is the logs you reported marked as error?

yes

**Comment by TapiocaFox** [comment]
Cool, thank you for patiently providing the information. It seems to affect Chinese language users. It will be fixed next version.
